// DO NOT EDIT.
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: ClientSearchUsername.proto
//
// For information on using the generated types, please see the documenation:
//   https://github.com/apple/swift-protobuf/

import Foundation
import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that your are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

struct IGPClientSearchUsername: SwiftProtobuf.Message {
  static let protoMessageName: String = "IGPClientSearchUsername"

  var igpRequest: IGPRequest {
    get {return _storage._igpRequest ?? IGPRequest()}
    set {_uniqueStorage()._igpRequest = newValue}
  }
  /// Returns true if `igpRequest` has been explicitly set.
  var hasIgpRequest: Bool {return _storage._igpRequest != nil}
  /// Clears the value of `igpRequest`. Subsequent reads from it will return its default value.
  mutating func clearIgpRequest() {_storage._igpRequest = nil}

  var igpQuery: String {
    get {return _storage._igpQuery}
    set {_uniqueStorage()._igpQuery = newValue}
  }

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  /// Used by the decoding initializers in the SwiftProtobuf library, not generally
  /// used directly. `init(serializedData:)`, `init(jsonUTF8Data:)`, and other decoding
  /// initializers are defined in the SwiftProtobuf library. See the Message and
  /// Message+*Additions` files.
  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    _ = _uniqueStorage()
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      while let fieldNumber = try decoder.nextFieldNumber() {
        switch fieldNumber {
        case 1: try decoder.decodeSingularMessageField(value: &_storage._igpRequest)
        case 2: try decoder.decodeSingularStringField(value: &_storage._igpQuery)
        default: break
        }
      }
    }
  }

  /// Used by the encoding methods of the SwiftProtobuf library, not generally
  /// used directly. `Message.serializedData()`, `Message.jsonUTF8Data()`, and
  /// other serializer methods are defined in the SwiftProtobuf library. See the
  /// `Message` and `Message+*Additions` files.
  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      if let v = _storage._igpRequest {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
      }
      if !_storage._igpQuery.isEmpty {
        try visitor.visitSingularStringField(value: _storage._igpQuery, fieldNumber: 2)
      }
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  fileprivate var _storage = _StorageClass.defaultInstance
}

struct IGPClientSearchUsernameResponse: SwiftProtobuf.Message {
  static let protoMessageName: String = "IGPClientSearchUsernameResponse"

  var igpResponse: IGPResponse {
    get {return _storage._igpResponse ?? IGPResponse()}
    set {_uniqueStorage()._igpResponse = newValue}
  }
  /// Returns true if `igpResponse` has been explicitly set.
  var hasIgpResponse: Bool {return _storage._igpResponse != nil}
  /// Clears the value of `igpResponse`. Subsequent reads from it will return its default value.
  mutating func clearIgpResponse() {_storage._igpResponse = nil}

  var igpResult: [IGPClientSearchUsernameResponse.IGPResult] {
    get {return _storage._igpResult}
    set {_uniqueStorage()._igpResult = newValue}
  }

  var unknownFields = SwiftProtobuf.UnknownStorage()

  struct IGPResult: SwiftProtobuf.Message {
    static let protoMessageName: String = IGPClientSearchUsernameResponse.protoMessageName + ".IGPResult"

    var igpType: IGPClientSearchUsernameResponse.IGPResult.IGPType {
      get {return _storage._igpType}
      set {_uniqueStorage()._igpType = newValue}
    }

    var igpExactMatch: Bool {
      get {return _storage._igpExactMatch}
      set {_uniqueStorage()._igpExactMatch = newValue}
    }

    var igpUser: IGPRegisteredUser {
      get {return _storage._igpUser ?? IGPRegisteredUser()}
      set {_uniqueStorage()._igpUser = newValue}
    }
    /// Returns true if `igpUser` has been explicitly set.
    var hasIgpUser: Bool {return _storage._igpUser != nil}
    /// Clears the value of `igpUser`. Subsequent reads from it will return its default value.
    mutating func clearIgpUser() {_storage._igpUser = nil}

    var igpRoom: IGPRoom {
      get {return _storage._igpRoom ?? IGPRoom()}
      set {_uniqueStorage()._igpRoom = newValue}
    }
    /// Returns true if `igpRoom` has been explicitly set.
    var hasIgpRoom: Bool {return _storage._igpRoom != nil}
    /// Clears the value of `igpRoom`. Subsequent reads from it will return its default value.
    mutating func clearIgpRoom() {_storage._igpRoom = nil}

    var unknownFields = SwiftProtobuf.UnknownStorage()

    enum IGPType: SwiftProtobuf.Enum {
      typealias RawValue = Int
      case user // = 0
      case room // = 1
      case UNRECOGNIZED(Int)

      init() {
        self = .user
      }

      init?(rawValue: Int) {
        switch rawValue {
        case 0: self = .user
        case 1: self = .room
        default: self = .UNRECOGNIZED(rawValue)
        }
      }

      var rawValue: Int {
        switch self {
        case .user: return 0
        case .room: return 1
        case .UNRECOGNIZED(let i): return i
        }
      }

    }

    init() {}

    /// Used by the decoding initializers in the SwiftProtobuf library, not generally
    /// used directly. `init(serializedData:)`, `init(jsonUTF8Data:)`, and other decoding
    /// initializers are defined in the SwiftProtobuf library. See the Message and
    /// Message+*Additions` files.
    mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
      _ = _uniqueStorage()
      try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
        while let fieldNumber = try decoder.nextFieldNumber() {
          switch fieldNumber {
          case 1: try decoder.decodeSingularEnumField(value: &_storage._igpType)
          case 2: try decoder.decodeSingularBoolField(value: &_storage._igpExactMatch)
          case 3: try decoder.decodeSingularMessageField(value: &_storage._igpUser)
          case 4: try decoder.decodeSingularMessageField(value: &_storage._igpRoom)
          default: break
          }
        }
      }
    }

    /// Used by the encoding methods of the SwiftProtobuf library, not generally
    /// used directly. `Message.serializedData()`, `Message.jsonUTF8Data()`, and
    /// other serializer methods are defined in the SwiftProtobuf library. See the
    /// `Message` and `Message+*Additions` files.
    func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
      try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
        if _storage._igpType != .user {
          try visitor.visitSingularEnumField(value: _storage._igpType, fieldNumber: 1)
        }
        if _storage._igpExactMatch != false {
          try visitor.visitSingularBoolField(value: _storage._igpExactMatch, fieldNumber: 2)
        }
        if let v = _storage._igpUser {
          try visitor.visitSingularMessageField(value: v, fieldNumber: 3)
        }
        if let v = _storage._igpRoom {
          try visitor.visitSingularMessageField(value: v, fieldNumber: 4)
        }
      }
      try unknownFields.traverse(visitor: &visitor)
    }

    fileprivate var _storage = _StorageClass.defaultInstance
  }

  init() {}

  /// Used by the decoding initializers in the SwiftProtobuf library, not generally
  /// used directly. `init(serializedData:)`, `init(jsonUTF8Data:)`, and other decoding
  /// initializers are defined in the SwiftProtobuf library. See the Message and
  /// Message+*Additions` files.
  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    _ = _uniqueStorage()
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      while let fieldNumber = try decoder.nextFieldNumber() {
        switch fieldNumber {
        case 1: try decoder.decodeSingularMessageField(value: &_storage._igpResponse)
        case 2: try decoder.decodeRepeatedMessageField(value: &_storage._igpResult)
        default: break
        }
      }
    }
  }

  /// Used by the encoding methods of the SwiftProtobuf library, not generally
  /// used directly. `Message.serializedData()`, `Message.jsonUTF8Data()`, and
  /// other serializer methods are defined in the SwiftProtobuf library. See the
  /// `Message` and `Message+*Additions` files.
  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      if let v = _storage._igpResponse {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
      }
      if !_storage._igpResult.isEmpty {
        try visitor.visitRepeatedMessageField(value: _storage._igpResult, fieldNumber: 2)
      }
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  fileprivate var _storage = _StorageClass.defaultInstance
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

extension IGPClientSearchUsername: SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .standard(proto: "IGP_request"),
    2: .standard(proto: "IGP_query"),
  ]

  fileprivate class _StorageClass {
    var _igpRequest: IGPRequest? = nil
    var _igpQuery: String = String()

    static let defaultInstance = _StorageClass()

    private init() {}

    init(copying source: _StorageClass) {
      _igpRequest = source._igpRequest
      _igpQuery = source._igpQuery
    }
  }

  fileprivate mutating func _uniqueStorage() -> _StorageClass {
    if !isKnownUniquelyReferenced(&_storage) {
      _storage = _StorageClass(copying: _storage)
    }
    return _storage
  }

  func _protobuf_generated_isEqualTo(other: IGPClientSearchUsername) -> Bool {
    if _storage !== other._storage {
      let storagesAreEqual: Bool = withExtendedLifetime((_storage, other._storage)) { (_args: (_StorageClass, _StorageClass)) in
        let _storage = _args.0
        let other_storage = _args.1
        if _storage._igpRequest != other_storage._igpRequest {return false}
        if _storage._igpQuery != other_storage._igpQuery {return false}
        return true
      }
      if !storagesAreEqual {return false}
    }
    if unknownFields != other.unknownFields {return false}
    return true
  }
}

extension IGPClientSearchUsernameResponse: SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .standard(proto: "IGP_response"),
    2: .standard(proto: "IGP_result"),
  ]

  fileprivate class _StorageClass {
    var _igpResponse: IGPResponse? = nil
    var _igpResult: [IGPClientSearchUsernameResponse.IGPResult] = []

    static let defaultInstance = _StorageClass()

    private init() {}

    init(copying source: _StorageClass) {
      _igpResponse = source._igpResponse
      _igpResult = source._igpResult
    }
  }

  fileprivate mutating func _uniqueStorage() -> _StorageClass {
    if !isKnownUniquelyReferenced(&_storage) {
      _storage = _StorageClass(copying: _storage)
    }
    return _storage
  }

  func _protobuf_generated_isEqualTo(other: IGPClientSearchUsernameResponse) -> Bool {
    if _storage !== other._storage {
      let storagesAreEqual: Bool = withExtendedLifetime((_storage, other._storage)) { (_args: (_StorageClass, _StorageClass)) in
        let _storage = _args.0
        let other_storage = _args.1
        if _storage._igpResponse != other_storage._igpResponse {return false}
        if _storage._igpResult != other_storage._igpResult {return false}
        return true
      }
      if !storagesAreEqual {return false}
    }
    if unknownFields != other.unknownFields {return false}
    return true
  }
}

extension IGPClientSearchUsernameResponse.IGPResult: SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .standard(proto: "IGP_type"),
    2: .standard(proto: "IGP_exact_match"),
    3: .standard(proto: "IGP_user"),
    4: .standard(proto: "IGP_room"),
  ]

  fileprivate class _StorageClass {
    var _igpType: IGPClientSearchUsernameResponse.IGPResult.IGPType = .user
    var _igpExactMatch: Bool = false
    var _igpUser: IGPRegisteredUser? = nil
    var _igpRoom: IGPRoom? = nil

    static let defaultInstance = _StorageClass()

    private init() {}

    init(copying source: _StorageClass) {
      _igpType = source._igpType
      _igpExactMatch = source._igpExactMatch
      _igpUser = source._igpUser
      _igpRoom = source._igpRoom
    }
  }

  fileprivate mutating func _uniqueStorage() -> _StorageClass {
    if !isKnownUniquelyReferenced(&_storage) {
      _storage = _StorageClass(copying: _storage)
    }
    return _storage
  }

  func _protobuf_generated_isEqualTo(other: IGPClientSearchUsernameResponse.IGPResult) -> Bool {
    if _storage !== other._storage {
      let storagesAreEqual: Bool = withExtendedLifetime((_storage, other._storage)) { (_args: (_StorageClass, _StorageClass)) in
        let _storage = _args.0
        let other_storage = _args.1
        if _storage._igpType != other_storage._igpType {return false}
        if _storage._igpExactMatch != other_storage._igpExactMatch {return false}
        if _storage._igpUser != other_storage._igpUser {return false}
        if _storage._igpRoom != other_storage._igpRoom {return false}
        return true
      }
      if !storagesAreEqual {return false}
    }
    if unknownFields != other.unknownFields {return false}
    return true
  }
}

extension IGPClientSearchUsernameResponse.IGPResult.IGPType: SwiftProtobuf._ProtoNameProviding {
  static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    0: .same(proto: "USER"),
    1: .same(proto: "ROOM"),
  ]
}
